version: "3.2"

services:
  lbh-fss-portal-api:
    image: lbh-fss-portal-api
    build:
      context: LBHFSSPortalAPI/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=entitycorex;Username=postgres;Password=mypassword
      - CLIENT_ID=$CLIENT_ID
      - COGNITO_USER=$COGNITO_USER
      - COGNITO_KEY=$COGNITO_KEY
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  lbh-fss-portal-api-test:
    image: lbh-fss-portal-api-test
    build:
      context: .
      dockerfile: LBHFSSPortalAPI.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env
